// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PetApp.Models;

#nullable disable

namespace PetApp.Migrations
{
    [DbContext(typeof(PetAppContext))]
    [Migration("20260603015522_DockerModelSync")]
    partial class DockerModelSync
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PetApp.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EhCastrado")
                        .HasColumnType("boolean");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<int>("IdCastracao")
                        .HasColumnType("integer");

                    b.Property<int>("IdTutor")
                        .HasColumnType("integer");

                    b.Property<int>("Idade")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Peso")
                        .HasColumnType("numeric");

                    b.Property<string>("Raca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.HasKey("Id");

                    b.HasIndex("IdTutor");

                    b.ToTable("Animais");
                });

            modelBuilder.Entity("PetApp.Models.Castracao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCastracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdAnimal")
                        .HasColumnType("integer");

                    b.Property<int>("IdClinica")
                        .HasColumnType("integer");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("IdAnimal")
                        .IsUnique();

                    b.HasIndex("IdClinica");

                    b.ToTable("Castracoes");
                });

            modelBuilder.Entity("PetApp.Models.Clinica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("VeterinarioResponsavel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clinicas");
                });

            modelBuilder.Entity("PetApp.Models.Tutor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.HasKey("Id");

                    b.ToTable("Tutores", t =>
                        {
                            t.HasCheckConstraint("CK_Tutores_Nome_NotEmpty", "\"Nome\" IS NOT NULL AND TRIM(\"Nome\") != ''");
                        });
                });

            modelBuilder.Entity("PetApp.Models.Animal", b =>
                {
                    b.HasOne("PetApp.Models.Tutor", "Tutor")
                        .WithMany("Animais")
                        .HasForeignKey("IdTutor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("PetApp.Models.Castracao", b =>
                {
                    b.HasOne("PetApp.Models.Animal", "Animal")
                        .WithOne("Castracao")
                        .HasForeignKey("PetApp.Models.Castracao", "IdAnimal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetApp.Models.Clinica", "Clinica")
                        .WithMany("Castracoes")
                        .HasForeignKey("IdClinica")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Clinica");
                });

            modelBuilder.Entity("PetApp.Models.Animal", b =>
                {
                    b.Navigation("Castracao");
                });

            modelBuilder.Entity("PetApp.Models.Clinica", b =>
                {
                    b.Navigation("Castracoes");
                });

            modelBuilder.Entity("PetApp.Models.Tutor", b =>
                {
                    b.Navigation("Animais");
                });
#pragma warning restore 612, 618
        }
    }
}
